
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: ao1538426
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate.format_sql: true

server:
  port : 8081